## Amazone_Dataset

In [1]:
#import necessary libraries
import pandas as pd
import numpy as np
import re
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv("D:\\Shubhamclassroom\\6th_Sem\\ml_lab\\prc3\\Amazon_Unlocked_Mobile.csv")
dataset.head()

Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  
0       5  I feel so LUCKY to have found this used (phone...           1.0  
1       4  nice phone, nice up grade from my pantach revu...           0.0  
2       5                                       Very pleased           0.0  
3       4  It works good but it goes slow sometimes but i...           0.0  
4       4  Great phone to replace my lost phone. The only...           0.0

In [3]:
labels = []
for cell in dataset['Rating']:
    if cell >= 4:
        labels.append('2')   #Good
    elif cell == 3:
        labels.append('1')   #Neutral
    else:
        labels.append('0')   #Poor
            
dataset['Label'] = labels
del dataset['Review Votes']

In [4]:
df=dataset[:50000]

In [5]:
df.isna().sum()

Product Name       0
Brand Name      8675
Price           1614
Rating             0
Reviews           13
Label              0
dtype: int64

In [6]:
X=df['Reviews']

In [7]:
X.isna().sum()

13

In [8]:
X.fillna('Good')

0        I feel so LUCKY to have found this used (phone...
1        nice phone, nice up grade from my pantach revu...
2                                             Very pleased
3        It works good but it goes slow sometimes but i...
4        Great phone to replace my lost phone. The only...
                               ...                        
49995                                           Works well
49996    Probably could've found better prices , also t...
49997      The iphone is unlock Good phone but bad ime att
49998    Don't buy it. Yes the iPhone is brand new and ...
49999    Phone arrived quickly as described and worked ...
Name: Reviews, Length: 50000, dtype: object

In [10]:
#change text lower cases and removal of white spaces
lower_text = []
for i in range(0,len(X)):
    s = str(X[i])
    s1 = s.strip()
    lower_text.append(s1.lower())

In [11]:
def remove_punctuation(test_str):
# Using filter() and lambda function to filter out punctuation characters
    result = ''.join(filter(lambda x: x.isalpha() or x.isdigit() or x.isspace(), test_str))
    return result

In [12]:
#Remove punctuation
punc_text = []
for i in range(0,len(lower_text)):
    s2 = (lower_text[i])
    s3 = remove_punctuation(s2)
    punc_text.append(s3)

In [13]:
y=df['Label']

In [14]:
y.isna().sum()

0

In [15]:
X.count()

49987

In [17]:
y.count()

50000

In [18]:
tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5,max_df = 0.7,norm='l2', encoding='latin-1', ngram_range=(1, 2),stop_words='english')


In [19]:
X_tfidf = tfidf.fit_transform(punc_text)

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X_tfidf, y, test_size=0.1, random_state=0)

In [21]:
clf = DecisionTreeClassifier()

In [22]:
clf.fit(X_train, Y_train)

DecisionTreeClassifier()

In [23]:
y_pred = clf.predict(X_test)
y_pred[:50]

array(['0', '0', '0', '2', '2', '2', '2', '2', '2', '2', '0', '2', '2',
       '0', '0', '0', '1', '1', '2', '2', '0', '2', '2', '0', '2', '2',
       '2', '2', '2', '0', '2', '2', '2', '2', '0', '0', '0', '2', '2',
       '0', '2', '1', '0', '2', '1', '0', '2', '2', '2', '2'],
      dtype=object)

In [24]:
print("Confusion Matrix\n",confusion_matrix(Y_test,y_pred))
print("\n")
print("Classification Report\n",classification_report(Y_test,y_pred))
print("\n")
print("Accuracy : ",accuracy_score(Y_test,y_pred)*100)

Confusion Matrix
 [[1152   19   82]
 [  26  249   46]
 [  55   18 3353]]


Classification Report
               precision    recall  f1-score   support

           0       0.93      0.92      0.93      1253
           1       0.87      0.78      0.82       321
           2       0.96      0.98      0.97      3426

    accuracy                           0.95      5000
   macro avg       0.92      0.89      0.91      5000
weighted avg       0.95      0.95      0.95      5000



Accuracy :  95.08
